### PR TITLE
Support single node as argument to microlink()

### PR DESCRIPTION
**Pull request by anthonylebrun**
Addresses issue #113

### CODE REVIEW

**Comment by anthonylebrun** [comment]
That does seem way better. Updated branch :)

**Comment by Kikobeats** [comment]
The thing that I'm not sure is, if this is necessary, why this is working?

https://github.com/microlinkhq/sdk/blob/master/packages/microlinkjs/public/index.html#L78

Also I think `each` is ensure to iterate the doom even if it is or not a collection

**Comment by anthonylebrun** [comment]
`getElementsByClassName` returns a `HTMLCollection`, so it makes sense that
it works. You can easily reproduce the error with `querySelector`.

**Comment by Kikobeats** [comment]
I added `querySelector` example
https://github.com/microlinkhq/sdk/commit/4d7374f09b854445816c26e7d9ba27fddf61f8b6

It looks that it's not possible iterate it with the current implementation :(

**Comment by Kikobeats** [comment]
Looks like it works `querySelectorAll` without adding more code, can we ensure a way that `querySelector` returns the same output than `querySelectorAll`?

**Comment by anthonylebrun** [comment]
I feel like we might be doing down a rabbit hole :)

`querySelectorAll` and `querySelector` are beside the point - like in my case I'm not using `querySelector` to get a dom node. I'm getting the dom node object via react's `ref` mechanism.

What I'm trying to achieve is this function signature (in pseudo code):

```
microlink(selector : HTMLElement)
```

(which currently doesn't work)

In addition to:

```
microlink(selector : Array(HTMLElement))
```

(which currently works)

**Pull request merged**
