### PR TITLE
Add "media expand" control

### PR DESCRIPTION
**Pull request by breadadams**
To-do:

* [ ] Video seems to restart _on expand_?

### CODE REVIEW

**Comment by Kikobeats** [comment]
should we create a specific section at storybook?

**Comment by breadadams** [comment]
Yeah, I'm thinking we expand on the `controls` prop, allowing for it to be an object of booleans as well as just a boolean.

I'll create an issue and explain further there, don't merge this yet 😛

**Comment by Kikobeats** [comment]
Do you think we still need that?

The main reset styles are related with vanilla bundle and we added a [recipe into doc](https://docs.microlink.io/sdk/getting-started/vanilla/#specifying-a-selector) to handle it properly

Feeling that this is enough

**Comment by Kikobeats** [comment]
> Video seems to restart on expand?

I not think so. You are seeing the video and you want to continue seeing it but on expand mode 🙂.

**Comment by breadadams** [comment]
Huh? Maybe you misunderstood, that's a "bug" left to fix with this implementation - the video restarts after toggling the size

**Comment by Kikobeats** [comment]
I made a commit doing a little changes:

- Add minimize button as well
- Just show the button on hover the video

**Comment by breadadams** [comment]
I ❤️ it @Kikobeats! However I'm now seeing why the video restarts when entering/leaving "expand mode". The whole component is re-rendering (including regenerating styled-component classnames):

microlink_card_rerender
(The classnames change in the gif as I'm toggling the expand control)

**Comment by breadadams** [comment]
I've made a couple of mostly style-related adjustments, as well as rebasing with `master`. Still can't figure out the _re-render_ issue though 🤔

**Comment by breadadams** [comment]
I was looking through the repo and saw this PR is still lingering @Kikobeats. I'd like to finish implementing it.

Do you think it's still a worthy feature? If so I will rebase from master and open an issue in styled-components if I can't resolve the re-rendering on className change.

**Pull request closed without merging**
