### PR TITLE
On toggle playback prop

### PR DESCRIPTION
**Pull request by narghev**
This PR adds an optional `onTogglePlayback` prop that accepts a callback and calls it when the playback of `audio` or `video` toggles.

### CODE REVIEW

**Comment by narghev** [comment]
This PR adds an optional `onTogglePlayback` prop that accepts a callback and calls it when the playback of `audio` or `video` toggles.

**Comment by breadadams** [comment]
Hi @narghev, see my comment here: https://github.com/microlinkhq/sdk/pull/231#issuecomment-633657697

**Comment by narghev** [comment]
Saw it. Should I close this PR?

> Hi @narghev, see my comment here: [#231 (comment)](https://github.com/microlinkhq/sdk/pull/231#issuecomment-633657697)

**Comment by breadadams** [comment]
I'll leave that decision to @Kikobeats, but I think so 👍

**Comment by Kikobeats** [comment]
yes, closing in favour of #231 🙂

**Pull request closed without merging**
